FROM nginx AS web

RUN apt-get update -qq && apt-get -y install apache2-utils

ENV APP /var/www/ror-ecs

WORKDIR $APP

RUN mkdir log

COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

COPY nginx.sh ./

RUN chmod 755 ./nginx.sh

CMD ["./nginx.sh"]