version: '3'
services:
  react:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile-APP
  web:
    build:
      context: .
      dockerfile: Dockerfile-NGINX
    container_name: nginx
    links:
      - react
    ports:
      - 80:80