version: '3' 
services:  
  react:
    image: 570604655849.dkr.ecr.ap-southeast-1.amazonaws.com/react
    build:      
      context: .
      dockerfile: Dockerfile-APP
  web:
    image: 570604655849.dkr.ecr.ap-southeast-1.amazonaws.com/nginx
    build:      
      context: .
      dockerfile: Dockerfile-NGINX
    links:      
      - react  
    ports:      
      - 80:80