apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: ingress-controller
spec:
  storageClassName: mystorageclass
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/v1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: ingress-controller
  labels:
    name: pvc
spec:
  storageClassName: mystorageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi