name: DOCS CI/CD Pipeline

on: push

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set tag var
        id: vars
        run: echo ::set-output name=docker_tag::$(echo ${GITHUB_SHA})

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: congttl/docs:${{ steps.vars.outputs.docker_tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  update-manifest:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://continuumio/anaconda3:2019.07

      - name: Set tag version
        id: vars
        run: echo ::set-output name=docker_tag::$(echo ${GITHUB_SHA})

      - name: authenticate git
        run: |
          git config --global user.name 'nguyenthanhcong101096'
          git config --global user.email 'nguyenthanhcong101096@gmail.com'
          git config --global credential.credentialStore ${{ secrets.TOKEN_GITHUB }}
          git config --global hub.protocol https

      - name: git clone
        run: git clone https://github.com/nguyenthanhcong101096/helm_chart.git
      
      - name: update manifest
        run: docker run --rm -v ${PWD}:/workdir mikefarah/yq:3.2.1 yq write --inplace --verbose helm_chart/values.yaml image.tag ${{ steps.vars.outputs.docker_tag }}

      - name: git commit & push to helm chart
        run: |
          cd helm_chart
          git add .
          git commit -am "Update K8S image"
          git push origin master
